joint_state_controller:
  type: "joint_state_controller/JointStateController"
  publish_rate: 50

left_wheel_ctrl:
  type: "velocity_controllers/JointVelocityController"
  joint: left_wheel

right_wheel_ctrl:
  type: "velocity_controllers/JointVelocityController"
  joint: right_wheel

front_wheel_ctrl:
  type: "velocity_controllers/JointVelocityController"
  joint: front_wheel